# In this notebook, a unit square mesh is used to show some basic commands which we will be using in fenics simulation.  
* Print the cordinates
* Save dof in xdmf file 
* Visualise the cell data and point data in Paraview

## Import dolfin module

In [1]:
from dolfin import *
import numpy as np

## Next two ways of using the mesh is shown
1. Importing mesh saved as xdmf file
2. Using the inbuilt mesh in dolfin

In [2]:
mesh = UnitSquareMesh(2, 2)

In [3]:
plot(mesh)

### Create the vector function apace in mesh 

In [4]:
V = VectorFunctionSpace(mesh, 'Lagrange', degree=1)

### DOF to vertex map

In [5]:
num_dof = mesh.num_vertices()*V.dofmap().num_entity_dofs(0)
dof_map = Function(V,name="dof")
dof_map.vector()[:] = [int(i) for i in np.linspace(0,num_dof-1,num_dof)]

### Save the dof in a xdmf file which can be visualised in Paraview
* Press V to visualise the cell and point data correspondng to a specific dof. 

In [6]:
with XDMFFile("dof.xdmf") as xdmf:
    xdmf.write(dof_map)

In [7]:
print(dof_map.vector()[:])

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.]


In [8]:
mesh.coordinates()

array([[0. , 0. ],
       [0.5, 0. ],
       [1. , 0. ],
       [0. , 0.5],
       [0.5, 0.5],
       [1. , 0.5],
       [0. , 1. ],
       [0.5, 1. ],
       [1. , 1. ]])

In [9]:
print(mesh.cells())

[[0 1 4]
 [0 3 4]
 [1 2 5]
 [1 4 5]
 [3 4 7]
 [3 6 7]
 [4 5 8]
 [4 7 8]]


In [42]:
V.tabulate_dof_coordinates()

array([[0., 1.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [1., 0.]])

In [10]:
mesh.num_cells()

8

In [45]:
mesh.num_edges()

5

In [11]:
mesh.num_vertices()

9